/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacotevisao;

import com.sun.awt.AWTUtilities;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import pacoDAO.produtoDAO;
import pacoteModelo.Produto;

/**
 *
 * @author Alexia
 */
public class CadProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadCliente
     */
    int x, y;
    public CadProduto() {
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this,false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void botoes(boolean novo, boolean salvar, boolean editar, boolean excluir){
        btnadcionar.setEnabled(novo);
        btnsalvar.setEnabled(salvar);
        btneditar.setEnabled(editar);
        btnexcluir.setEnabled(excluir);
        //btnexcluir.setEnabled(consultar);
    }
    private void carregarFormulario(Produto p) {

        txtcodigo.setText( String.valueOf(p.getCodigo()) );
        txtnome.setText(p.getNome());                         
        txtmarca.setText(p.getMarca());
        txtsaldo.setText( String.valueOf( p.getSaldo()) );
        txtcodigodebarras.setText( String.valueOf( p.getCodigodebarras()) );
        txtpesobruto.setText( String.valueOf( p.getPesob()) );
        txtpesoliquido.setText( String.valueOf( p.getPesol()) );
        txtpreco.setText( String.valueOf( p.getPreco()) );
        txtunidade.setText( String.valueOf( p.getUnidade()) );

    }
    private void limparCampos(){
     txtcodigodebarras.setText("");
     txtconsultaprod.setText("");
     txtmarca.setText("");
     txtnome.setText("");
     txtpesobruto.setText("");
     txtpesoliquido.setText("");
     txtpreco.setText("");
     txtsaldo.setText("");
     txtunidade.setText("");
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        txtcodigo = new javax.swing.JTextField();
        txtpreco = new javax.swing.JTextField();
        txtunidade = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        txtcodigodebarras = new javax.swing.JTextField();
        txtpesoliquido = new javax.swing.JTextField();
        txtmarca = new javax.swing.JTextField();
        txtsaldo = new javax.swing.JTextField();
        txtpesobruto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtconsultaprod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTproduto = new javax.swing.JTable();
        btnadcionar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        btnvoltar = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setUndecorated(true);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jTabbedPane2.setBackground(new java.awt.Color(255, 51, 51));
        jTabbedPane2.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(169, 209, 142));
        jPanel3.setLayout(null);

        txtcodigo.setBorder(null);
        txtcodigo.setOpaque(false);
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        jPanel3.add(txtcodigo);
        txtcodigo.setBounds(20, 40, 230, 30);

        txtpreco.setBorder(null);
        txtpreco.setOpaque(false);
        jPanel3.add(txtpreco);
        txtpreco.setBounds(370, 240, 230, 30);

        txtunidade.setBorder(null);
        txtunidade.setOpaque(false);
        txtunidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunidadeActionPerformed(evt);
            }
        });
        jPanel3.add(txtunidade);
        txtunidade.setBounds(10, 120, 230, 30);

        txtnome.setBorder(null);
        txtnome.setOpaque(false);
        jPanel3.add(txtnome);
        txtnome.setBounds(340, 40, 440, 30);

        txtcodigodebarras.setBorder(null);
        txtcodigodebarras.setOpaque(false);
        jPanel3.add(txtcodigodebarras);
        txtcodigodebarras.setBounds(10, 230, 230, 30);

        txtpesoliquido.setBorder(null);
        txtpesoliquido.setOpaque(false);
        jPanel3.add(txtpesoliquido);
        txtpesoliquido.setBounds(670, 230, 230, 30);

        txtmarca.setBorder(null);
        txtmarca.setOpaque(false);
        jPanel3.add(txtmarca);
        txtmarca.setBounds(380, 120, 230, 30);

        txtsaldo.setBorder(null);
        txtsaldo.setOpaque(false);
        jPanel3.add(txtsaldo);
        txtsaldo.setBounds(660, 410, 230, 30);

        txtpesobruto.setBorder(null);
        txtpesobruto.setOpaque(false);
        jPanel3.add(txtpesobruto);
        txtpesobruto.setBounds(670, 130, 230, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/entrada2.png"))); // NOI18N
        jLabel6.setToolTipText("");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(0, 110, 260, 60);

        jLabel5.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel5.setText("Saldo");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(750, 370, 60, 30);

        jLabel9.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel9.setText("Nome do produto");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(490, 10, 140, 30);

        jLabel11.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel11.setText("Peso Bruto");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(740, 90, 100, 20);

        jLabel14.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel14.setText("Codigo de barras");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(60, 180, 160, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/entrada2.png"))); // NOI18N
        jLabel13.setToolTipText("");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(650, 400, 260, 60);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/entrada2.png"))); // NOI18N
        jLabel16.setToolTipText("");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(0, 220, 260, 60);

        jLabel21.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel21.setText("Unidade");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(90, 80, 80, 30);

        jLabel24.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel24.setText("Imagem");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(100, 320, 70, 30);

        jLabel28.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel28.setText("Preço");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(450, 200, 60, 30);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/entrada2.png"))); // NOI18N
        jLabel30.setToolTipText("");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(660, 220, 260, 60);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/entrada2.png"))); // NOI18N
        jLabel23.setToolTipText("");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(240, 520, 260, 60);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/entrada2.png"))); // NOI18N
        jLabel31.setToolTipText("");
        jPanel3.add(jLabel31);
        jLabel31.setBounds(360, 230, 260, 60);

        jLabel32.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel32.setText("Peso Liquido");
        jPanel3.add(jLabel32);
        jLabel32.setBounds(750, 190, 120, 30);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/entrada2.png"))); // NOI18N
        jLabel35.setToolTipText("");
        jPanel3.add(jLabel35);
        jLabel35.setBounds(660, 120, 260, 60);

        jLabel36.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel36.setText("Marca");
        jPanel3.add(jLabel36);
        jLabel36.setBounds(460, 80, 60, 30);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/entrada.png"))); // NOI18N
        jLabel34.setToolTipText("");
        jPanel3.add(jLabel34);
        jLabel34.setBounds(330, 30, 460, 60);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/entrada2.png"))); // NOI18N
        jLabel39.setToolTipText("");
        jPanel3.add(jLabel39);
        jLabel39.setBounds(370, 110, 260, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/entrada2.png"))); // NOI18N
        jLabel7.setToolTipText("");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 30, 260, 60);

        jLabel22.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel22.setText("Código");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(90, 10, 80, 30);

        jTabbedPane2.addTab("Produto", jPanel3);

        jPanel2.setBackground(new java.awt.Color(169, 209, 142));
        jPanel2.setLayout(null);

        txtconsultaprod.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        txtconsultaprod.setBorder(null);
        txtconsultaprod.setOpaque(false);
        jPanel2.add(txtconsultaprod);
        txtconsultaprod.setBounds(30, 80, 440, 30);

        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel1.setText("Nome do produto");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(160, 30, 150, 19);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/entrada.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 70, 500, 60);

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(530, 80, 90, 23);

        jTproduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Marca", "Preco"
            }
        ));
        jTproduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTprodutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTproduto);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 850, 290);

        jTabbedPane2.addTab("Consulta", jPanel2);

        jPanel1.add(jTabbedPane2);
        jTabbedPane2.setBounds(40, 150, 900, 500);

        btnadcionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/adicionar.png"))); // NOI18N
        btnadcionar.setBorder(null);
        btnadcionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadcionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnadcionar);
        btnadcionar.setBounds(330, 60, 80, 70);

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/editarcliente.png"))); // NOI18N
        btneditar.setBorder(null);
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        jPanel1.add(btneditar);
        btneditar.setBounds(580, 60, 80, 70);

        btnsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/confirmar.png"))); // NOI18N
        btnsalvar.setBorder(null);
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalvar);
        btnsalvar.setBounds(440, 60, 90, 70);

        btnexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/excluir.png"))); // NOI18N
        btnexcluir.setBorder(null);
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnexcluir);
        btnexcluir.setBounds(690, 60, 80, 70);

        btnvoltar.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        btnvoltar.setText("Voltar");
        btnvoltar.setBorder(null);
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnvoltar);
        btnvoltar.setBounds(770, 650, 73, 23);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/fundo2.png"))); // NOI18N
        jPanel1.add(Fundo);
        Fundo.setBounds(10, 0, 1040, 700);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnadcionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadcionarActionPerformed
      
        
        limparCampos();
        botoes(false, true, false, false);
        txtcodigo.requestFocus();
        
        
        
    }//GEN-LAST:event_btnadcionarActionPerformed

    private void txtunidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunidadeActionPerformed

    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
        // TODO add your handling code here:
         new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnvoltarActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
      
    String sMensagem, sTitulo;
        int iResposta;
        sMensagem = "Deseja realmente excluir o Produto?";
        sTitulo = "Confirmação";
        iResposta = JOptionPane.showConfirmDialog(null, sMensagem, sTitulo, JOptionPane.YES_NO_OPTION);
        if(iResposta == JOptionPane.YES_OPTION){
            produtoDAO bd = new produtoDAO();
            bd.excluirProduto(Integer.parseInt(txtcodigo.getText()));
        }
        botoes(true, false, false, true);
        limparCampos();
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
        Produto p = new Produto();
        p.setCodigo          (Integer.parseInt  (txtcodigo.getText()));
        p.setNome            (txtnome.getText());
        p.setMarca           (txtmarca.getText());
        p.setSaldo           (Double.parseDouble(txtsaldo.getText()));
        p.setCodigodebarras  (Integer.parseInt  (txtcodigodebarras.getText()));
        p.setUnidade         (Integer.parseInt  (txtunidade.getText()));
        p.setPesob           (Double.parseDouble(txtpesobruto.getText()));
        p.setPesol           (Double.parseDouble(txtpesoliquido.getText()));
        p.setPreco           (Double.parseDouble(txtpreco.getText()));
        
        
        
        
        
        produtoDAO bd = new produtoDAO();
        bd.adcionarProduto(p);
        limparCampos();
        
        botoes(true, false, false, false);
        txtcodigo.requestFocus();
        
        
        
        
        
        
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        produtoDAO bd;
	Produto p;

	List<Produto> listaPrduto;
	bd = new produtoDAO();
	p = new Produto();
	listaPrduto = bd.consultarProdutoPorNome(txtconsultaprod.getText());

	DefaultTableModel model = (DefaultTableModel)
	jTproduto.getModel();

	model.setNumRows(0);

	for( int itemLista = 0; itemLista < listaPrduto.size(); itemLista++){
		p = listaPrduto.get(itemLista);
		model.addRow(new Object[] { p.getCodigo(), p.getNome(), p.getMarca(), p.getPreco() });
	}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
         produtoDAO bd;
        Produto p;
        p = new Produto();
        p.setCodigo(Integer.parseInt(txtcodigo.getText()));
        p.setNome(txtnome.getText());
        p.setMarca(txtnome.getText());
        p.setSaldo(Double.parseDouble(txtsaldo.getText()));
        p.setCodigodebarras(Integer.parseInt(txtcodigodebarras.getText()));
        p.setUnidade(Integer.parseInt  (txtunidade.getText()));
        p.setPesob(Double.parseDouble(txtpesobruto.getText()));
        p.setPesol(Double.parseDouble(txtpesoliquido.getText()));
        p.setPreco(Double.parseDouble(txtpreco.getText()));
        
        bd = new produtoDAO();
        bd.editarProduto(p);
        limparCampos();
        botoes(true, false,false,true);
    }//GEN-LAST:event_btneditarActionPerformed

    private void jTprodutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTprodutoMouseClicked
        // TODO add your handling code here:
        int iCodigo;

        iCodigo =  (int) jTproduto.getModel().getValueAt(jTproduto.getSelectedRow(),0);

        produtoDAO bd;

        bd = new produtoDAO();

        Produto p;

        p = new Produto();

        p = bd.procurarProdutoporCodigo(iCodigo);

        carregarFormulario(p);

        botoes(false, false, true, true);

        jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_jTprodutoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                }catch (Exception e){
                    
                }
                new CadProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton btnadcionar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTproduto;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcodigodebarras;
    private javax.swing.JTextField txtconsultaprod;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtpesobruto;
    private javax.swing.JTextField txtpesoliquido;
    private javax.swing.JTextField txtpreco;
    private javax.swing.JTextField txtsaldo;
    private javax.swing.JTextField txtunidade;
    // End of variables declaration//GEN-END:variables
}
