/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacotevisao;

import com.sun.awt.AWTUtilities;
import javax.swing.UIManager;


/**
 *
 * @author Alexia
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    int x, y;
    public Menu() {
        initComponents();        
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this,false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btncliente = new javax.swing.JButton();
        btnproduto = new javax.swing.JButton();
        btnfrantecaixa = new javax.swing.JButton();
        btnconsulta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(909, 909));
        setUndecorated(true);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("FAMA");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(390, 200, 290, 150);

        btncliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btncliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/Cliente.png"))); // NOI18N
        btncliente.setBorder(null);
        btncliente.setBorderPainted(false);
        btncliente.setContentAreaFilled(false);
        btncliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btncliente.setMinimumSize(new java.awt.Dimension(200, 211));
        btncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclienteActionPerformed(evt);
            }
        });
        jPanel1.add(btncliente);
        btncliente.setBounds(250, 50, 280, 100);

        btnproduto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnproduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/produtos.png"))); // NOI18N
        btnproduto.setBorder(null);
        btnproduto.setBorderPainted(false);
        btnproduto.setContentAreaFilled(false);
        btnproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprodutoActionPerformed(evt);
            }
        });
        jPanel1.add(btnproduto);
        btnproduto.setBounds(70, 180, 280, 110);

        btnfrantecaixa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnfrantecaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/frente de caixa.png"))); // NOI18N
        btnfrantecaixa.setBorder(null);
        btnfrantecaixa.setBorderPainted(false);
        btnfrantecaixa.setContentAreaFilled(false);
        btnfrantecaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfrantecaixaActionPerformed(evt);
            }
        });
        jPanel1.add(btnfrantecaixa);
        btnfrantecaixa.setBounds(50, 370, 300, 110);

        btnconsulta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnconsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/terminal de consulta.png"))); // NOI18N
        btnconsulta.setBorder(null);
        btnconsulta.setBorderPainted(false);
        btnconsulta.setContentAreaFilled(false);
        jPanel1.add(btnconsulta);
        btnconsulta.setBounds(180, 510, 290, 110);

        jLabel1.setFont(new java.awt.Font("Brush Script MT", 1, 30)); // NOI18N
        jLabel1.setText("POO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 390, 70, 40);

        jLabel4.setFont(new java.awt.Font("Brush Script MT", 1, 30)); // NOI18N
        jLabel4.setText("Alexia Vasconcellos");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(430, 430, 230, 40);

        jLabel5.setFont(new java.awt.Font("Brush Script MT", 1, 30)); // NOI18N
        jLabel5.setText("Sistemas de informação");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(400, 340, 310, 40);

        jLabel6.setFont(new java.awt.Font("Brush Script MT", 1, 20)); // NOI18N
        jLabel6.setText("Sair");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(390, 610, 40, 50);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacoteImagens/circulo.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 0, 723, 675);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclienteActionPerformed
        
      
        new CadCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnclienteActionPerformed

    private void btnprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprodutoActionPerformed
        // TODO add your handling code here:
         new CadProduto().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnprodutoActionPerformed

    private void btnfrantecaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfrantecaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnfrantecaixaActionPerformed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        x=evt.getX();
        y=evt.getY();

    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x +evt.getX()-x, this.getLocation().y + evt.getY() -y);

    }//GEN-LAST:event_jLabel3MouseDragged

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                }catch (Exception e){
                    
                }
                new Menu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncliente;
    private javax.swing.JButton btnconsulta;
    private javax.swing.JButton btnfrantecaixa;
    private javax.swing.JButton btnproduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
